### ISSUE TITLE
How to help when no data

### ISSUE THREAD

**Issue by martincollignon** [electricitymap/electricitymap-contrib#1977] opened 2019-09-28 08:03 UTC
Instead of just "No data available", we could also write a CTA? "Help out!"
We could give pointers on where to look for data / which organization to reach out to. 
That would also help non technical individuals to get onboard as contributors.

**Comment by fbarl** [comment] 2020-01-16 10:35
What I'm currently seeing when clicking on a zone (together with the CTA link) seems to fully address your concern:

![image](https://user-images.githubusercontent.com/1216874/72517077-0bd26400-3853-11ea-863d-69bf6e494fd4.png)

I'm confused because this seems to have been around before you opened this issue though :thinking: 

Maybe I'm misundertanding what the issue is about - is there another "No data available" somewhere else besides the map tooltip?

**Comment by systemcatch** [comment] 2020-01-30 15:14
@fbarl we could also add something like #1981 and maybe link to the github issue for the zone.

**Comment by fbarl** [comment] 2020-02-15 15:46
> we could also add something like #1981 and maybe link to the github issue for the zone.

That sounds like a great idea! Do you think we could continue the discussion there and close this issue? Or would you still like to keep this one around as an umbrella issue?

> Also as another idea, when a parser is down maybe we could include a link to the relevant log messages?

Also sounds like a useful thing but maybe more for developers than general end users. I'm curious,  do we currently have any publicly available links to parser logs?

**Comment by systemcatch** [comment] 2020-02-16 19:18
> That sounds like a great idea! Do you think we could continue the discussion there and close this issue? Or would you still like to keep this one around as an umbrella issue?

I think it's useful to keep this one around for now, do you have any thoughts how we can get more people involved in helping to find/generate more data sources?

> Also sounds like a useful thing but maybe more for developers than general end users. I'm curious, do we currently have any publicly available links to parser logs?

There is the link to the logger in the readme (https://github.com/tmrowco/electricitymap-contrib#logger) but given that I've never seen anyone outside the main contributors link to it I think many either don't know about it or don't really understand how it works.

**Comment by fbarl** [comment] 2020-02-20 11:03
> There is the link to the logger in the readme (https://github.com/tmrowco/electricitymap-contrib#logger) but given that I've never seen anyone outside the main contributors link to it I think many either don't know about it or don't really understand how it works.

Oh that's great! I opened #2230 to have a separate discussion about it there, but it seems like a very low hanging fruit to me since the logging itself is already implemented :)

> do you have any thoughts how we can get more people involved in helping to find/generate more data sources?

That's a good question worth everyone's attention. My general feeling is that the current Github documentation already provides good explanations and examples but what is sometimes missing are the flows that tie it all together. So instead of listing all my ideas on minor improvements we could make, I would suggest we try to formalize the _stages_ of work done on each region and use it as a basis to track progress internally and also for adding different CTAs / instructions for each stage separately. The stages I currently see are (subjectively):

1. **No live data sources have been found for the area** - this is currently true for most of the regions not represented in [this table](https://github.com/tmrowco/electricitymap-contrib#real-time-electricity-data-sources)

![image](https://user-images.githubusercontent.com/1216874/74926068-9ae41600-53d5-11ea-9280-fdef70bdd55f.png)

2. **A data source has been suggested but no parsers have been written yet** - like 1. except that we have a link to a potential live data provider for the region so we could tell users to use the link to write a parser (see #1981)
3. **A parser for the area exists but is broken (not providing any data)** - we could tell users to look into the logger to debug the parser (see #2230)

![image](https://user-images.githubusercontent.com/1216874/74926699-9a984a80-53d6-11ea-90b2-0b7943a41933.png)

4. **Partial consumption / exchange data is available** - we could tell users to contribute by writting more parsers

![image](https://user-images.githubusercontent.com/1216874/74926767-b3086500-53d6-11ea-9c77-2522034c19ee.png)

5. **Complete consumption / exchange data is available** - the data is complete (not sure if we have any region like that and also how we'd be able to verify it with confidence :thinking:)

Different users might want to engage at different stages depending on their personal skills and interests, so if we were able to deduct a stage each region is in, we could help them focus their engagement on a preferred stage rather than region.

WDYT @systemcatch @corradio ?

**Comment by systemcatch** [comment] 2020-02-20 15:12
@fbarl I think you nailed it with this part

> I would suggest we try to formalize the stages of work done on each region and use it as a basis to track progress internally and also for adding different CTAs / instructions for each stage separately. 

The only step I would add is between 1-2 where we know the data controller and want to get people  to apply pressure to them to release the data (described in #1981)

By implementing these steps we can turn passive users into active contributors!

**Comment by corradio** [comment] 2020-02-20 16:06
Fully agree, very good overview @fbarl .
Any idea on how to structure things? Maybe updating the labels for our github issues would be a good start? And maybe also have clear CTAs on each stage in our UI?
cc @robertahunt

**Comment by madsnedergaard** [comment] 2022-04-25 17:10
There's some good ideas here, and several have already been implemented.
The remaining ideas are great, but requires high maintenance - we're instead using [this issue](https://github.com/electricitymap/electricitymap-contrib/issues/3933) for keeping an overview of countries and their status :)

**Closed by madsnedergaard** 2022-04-25 17:10 UTC
Labels: idea 💡
