### ISSUE TITLE
New additions to the Faroe Islands grid

### ISSUE THREAD

**Issue by Bjarkigd** [electricitymap/electricitymap-contrib#2848] opened 2020-12-14 19:43 UTC
There have been added a bit of new renewables in the Faroes, and the website is finally showing the production. 

https://www.sev.fo/framleidsla/el-orka-i-foroyum/ 

Vindorka - Wind has had +6.3 MW installed since last update. 18+MW will be added next year if all permits etc go the right way.
Biogasorka - Biogas is a new thing with with 1.5 MW installed capacaty
Sólorka - Solar, is new as well, not much with 0.24MW installed capacity at one solar farm
There are also two solar roof installations(that I know of, there are probably more out there) with public data, two 12kW installations that can be seen here http://os.fo/ out to the right "sólórka á.....". Don't know if solar is even going to make a blip on the graph even in summer, but there's absolutely growing interest for it.

In addition to this there's a new trial tidal power thing, which is supplying energy to the grid, but it is small 100kW and doesn't show live generation, but it's planned for more next year.

If anyone wants to update it then feel free.

**Comment by q--** [comment] 2020-12-14 21:17
Thanks for the heads-up.

I had a look at the FO parser and it's currently using https://w3.sev.fo/hagtol/xml/xkiefjSDKFjeijgjdkjf3847tgfjlkfdgnlsnfvm.xml as its data source. I can't find solar production in it (Ctrl+F Sol gives me nothing).

The production page you linked is also fetching its data from a different source than that, namely https://www.sev.fo/api/realtimemap/now. So now I'm wondering if it's still being updated with new sources. (Output on the SEV site is pretty close to that on ElectricityMap and could easily be explained by a bit of lag, so I'm unsure. However, the new URL *does* have results for Ctrl+F Sol, so it's at least missing solar.)

Is the solar actually showing up on Sev.fo or should it be fetched from http://os.fo? It's night there now so I can't check

**Comment by q--** [comment] 2020-12-14 21:27
And to return to the subject of installed capacity, I was wondering if you've found a new source for the capacity data that can be listed in [DATA_SOURCES](https://github.com/tmrowco/electricitymap-contrib/blob/master/DATA_SOURCES.md)? 

The current source is a thesis paper that's obviously not getting updated (in fact, it's gone from the website) so if you've found a new source for this data that would be great 👍

**Comment by Bjarkigd** [comment] 2020-12-15 00:14
The old parser uses an old map (this one https://w3.sev.fo/framleidsla/ ) which probably at some point in the near future will go inactive, the utilities entire website has been relaunched/remade. So I would recommend just taking all data from the new site that I linked, which has launced sometime during the last week. The old one as you stated is missing solar, but also the biogas, and the added 6.3MW windfarm (Porkeri), so it would naturally be showing less output.

The rooftop solar is not included in sev.fo, so that would have to be fetched from os.fo 

The installed capacity can be found here https://www.sev.fo/um-okkum/elskipanin/orkuverk/ it's however missing one windfarm (Named Røkt in the maps)  as it isn't sev that owns it. Same with the biogas plant. And a bunch of smaller standalone "offgrid" diesel engines on the smaller islands.

I can contact them and ask if they could make a small update of some sort, adding the missing capacity in some way to their site.

**Comment by q--** [comment] 2020-12-15 10:22
>I can contact them and ask if they could make a small update of some sort, adding the missing capacity in some way to their site.

Thanks, yes, that would be nice. I had a look if I could find any other sources this, but the closest I got was a mention of Røkt on [Wikipedia](https://en.wikipedia.org/wiki/SEV_\(company\)) citing [a now-removed SEV.fo page (Google cache)](https://webcache.googleusercontent.com/search?q=cache:http://www.sev.fo/Default.aspx%3FID=123) that didn't actually mention Røkt. So having an overview of all Faroe power plants would be handy.

I'll try to update the parser to the new source

**Comment by Bjarkigd** [comment] 2020-12-15 17:09
> Thanks, yes, that would be nice. I had a look if I could find any other sources this, but the closest I got was a mention of Røkt on [Wikipedia](https://en.wikipedia.org/wiki/SEV_(company)) citing [a now-removed SEV.fo page (Google cache)](https://webcache.googleusercontent.com/search?q=cache:http://www.sev.fo/Default.aspx%3FID=123) that didn't actually mention Røkt. So having a complete overview of all Faroe power plants would be handy.

I've found a source on the capacity of Røkt, it's from a textbook, but still valid (long link) 3x660 kW = 1,98MW. https://books.google.com/books?id=mtPgM068hxkC&pg=PA186&lpg=PA186&dq=r%C3%B8kt+vindmyllur&source=bl&ots=Gv30-shbQ0&sig=ACfU3U3uqMtgY7VKMiZ7t-z-CRTwHH2hTg&hl=da&sa=X&ved=2ahUKEwjty-uiu9DtAhXpk4sKHePZB704ChDoATACegQIARAC#v=onepage&q=r%C3%B8kt%20vindmyllur&f=false

**Comment by Kongkille** [comment] 2022-04-28 11:17
This should have been closed as of #2849 :)

**Closed by Kongkille** 2022-04-28 11:17 UTC

**Comment by q--** [comment] 2022-04-28 12:15
The parser was handled in that one, but the installed capacity hasn't been updated AFAIK. The problem is (was? it's been a while since I looked) that SEV only lists own generation assets, not those owned by third parties, and the original paper that was the basis for FO installed capacity is gone from the Internet. @Bjarkigd made a few useful suggestions, but I'm not sure if we aren't still missing any generators that were known when calculating the original installed capacity.
