### ISSUE TITLE
Historical graphs overlap with vertical axis

### ISSUE THREAD

**Issue by corradio** [electricitymap/electricitymap-contrib#3586] opened 2021-12-06 07:05 UTC
Checked today (2021-12-06) at 08:02:

![image](https://user-images.githubusercontent.com/1655848/144802056-135a813a-2fbc-49bd-8483-c1a4cdf90e3a.png)

I've attached the `state` and `history` object so this can be reproduced:
[data.js.zip](https://github.com/tmrowco/electricitymap-contrib/files/7658647/data.js.zip)

**Comment by Kongkille** [comment] 2022-08-02 08:21
I am not able to reproduce this anymore, closing for now!

**Closed by Kongkille** 2022-08-02 08:21 UTC
Labels: bug 🐞
