### ISSUE TITLE
Attempting display of wind or solar causes a fault

### ISSUE THREAD

**Issue by rogercashmore** [electricitymap/electricitymap-contrib#4127] opened 2022-05-16 10:20 UTC
This has been solved in the past

**Comment by ajoga** [comment] 2022-05-16 10:27
Isn't this issue a duplicate of #4124 ?

**Comment by madsnedergaard** [comment] 2022-05-16 11:11
Yes, it should work now in latest version (that was released just before this issue was created) :)

**Closed by madsnedergaard** 2022-05-16 11:11 UTC
