### ISSUE TITLE
NZ down

### ISSUE THREAD

**Issue by drc38** [electricitymap/electricitymap-contrib#3870] opened 2022-03-17 08:46 UTC
https://storage.googleapis.com/electricitymap-parser-logs/NZ.html

However when running the parser script locally it successfully returns the following :
```
fetch_production(NZ) ->
{'zoneKey': 'NZ', 'datetime': datetime.datetime(2022, 3, 17, 7, 0, tzinfo=tzutc()), 'production': {'coal': 181, 'oil': 0, 'gas': 860, 'geothermal': 865, 'wind': 338, 'hydro': 2750, 'unknown': 135, 'nuclear': 0}, 'capacity': {'coal': 750, 'oil': 156, 'gas': 1280, 'geothermal': 1062, 'wind': 1040, 'hydro': 5415, 'battery storage': 1, 'unknown': 216, 'nuclear': 0}, 'storage': {'battery': 1}, 'source': 'transpower.co.nz'}
```
Any ideas on why the errors are occurring?

**Comment by Kongkille** [comment] 2022-03-17 09:39
I also get the issue locally. Are you using the test_parser script?  

`
(.venv) ➜  electricitymap-contrib git:(master) poetry run test_parser NZ
2022-03-17 10:37:43,066 DEBUG    urllib3.connectionpool         Starting new HTTPS connection (1): www.transpower.co.nz:443
2022-03-17 10:37:44,914 DEBUG    urllib3.connectionpool         https://www.transpower.co.nz:443 "GET /power-system-live-data HTTP/1.1" 200 25774
Parser result:
{'capacity': {'battery storage': 1,
              'coal': 750,
              'gas': 1280,
              'geothermal': 1062,
              'hydro': 5415,
              'nuclear': 0,
              'oil': 156,
              'unknown': 216,
              'wind': 1040},
 'datetime': datetime.datetime(2022, 3, 17, 9, 0, tzinfo=tzutc()),
 'production': {'coal': 141,
                'gas': 743,
                'geothermal': 870,
                'hydro': 2199,
                'nuclear': 0,
                'oil': 0,
                'unknown': 151,
                'wind': 326},
 'source': 'transpower.co.nz',
 'storage': {'battery': 0},
 'zoneKey': 'NZ'}
---------------------
took 1.93s
min returned datetime: 2022-03-17T09:00:00+00:00 UTC
max returned datetime: 2022-03-17T09:00:00+00:00 UTC  -- OK, <2h from now :) (now=2022-03-17T09:37:44.985702+00:00 UTC)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/markuskillendahl/Documents/Github/electricitymap-contrib/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/markuskillendahl/Documents/Github/electricitymap-contrib/.venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/markuskillendahl/Documents/Github/electricitymap-contrib/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/markuskillendahl/Documents/Github/electricitymap-contrib/.venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/markuskillendahl/Documents/Github/electricitymap-contrib/test_parser.py", line 118, in test_parser
    validate_production(event, zone)
  File "/Users/markuskillendahl/Documents/Github/electricitymap-contrib/parsers/lib/quality.py", line 156, in validate_production
    if key not in emission_factors(zone_key).keys():
  File "/Users/markuskillendahl/Documents/Github/electricitymap-contrib/electricitymap/contrib/config/__init__.py", line 49, in emission_factors
    return dict([(k, (v or {}).get("value")) for (k, v) in merged.items()])
  File "/Users/markuskillendahl/Documents/Github/electricitymap-contrib/electricitymap/contrib/config/__init__.py", line 49, in <listcomp>
    return dict([(k, (v or {}).get("value")) for (k, v) in merged.items()])
AttributeError: 'list' object has no attribute 'get'
`

**Comment by Kongkille** [comment] 2022-03-17 09:43
It seems the issue is coming from the validate_production step in quality.py and not the actual fetching from NZ. Looking at it briefly, it seems the issue is that it is looking for the "NZ" key in co2eq parameters to validate production types but cannot find it as we store the north and south part separately and don't have a combined one.

I believe the fix would be to merge the two entries in co2eq parameters into one NZ entry. 

Let me know if anyone wants to have a go at it, otherwise I'll add it to my list

**Comment by drc38** [comment] 2022-03-17 20:16
I've had a go correcting in #3872

**Closed** 2022-03-18 06:23 UTC
Labels: help wanted, parser
