### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Cez-16** [electricitymap/electricitymap-contrib#4005] opened 2022-04-24 11:19 UTC
Plus aucun affichage des valeurs sur l'ensemble de la carte

**Comment by VIKTORVAV99** [comment] 2022-04-25 10:51
This appears to be a duplicate of #3988?

If it is I suggest you close this and add more information to that issue instead @Cez-16.

**Comment by madsnedergaard** [comment] 2022-04-25 18:18
Cool that you joined Github and created this issue! 💪 
I'm also not sure if this is the same as #3988, but that one is currently being fixed and should be back up within the week. 
Please let us know here if you meant something else, otherwise we'll consider it done when the other fix is released :)

**Comment by ajoga** [comment] 2022-05-16 10:36
@madsnedergaard your linked issue has been fixed by #4009, could you close this issue as well ?

**Comment by madsnedergaard** [comment] 2022-05-16 11:12
Good point, closing this for now - feel free to reopen if this issue was about something else :)

**Closed by madsnedergaard** 2022-05-16 11:12 UTC
