### ISSUE TITLE
PV CO2/kWh value should vary per region

### ISSUE THREAD

**Issue by GiacomoFornaro** [electricitymap/electricitymap-contrib#4253] opened 2022-06-15 11:15 UTC
Hi electricitymap team,
I'd like to propose an upgrade on your PV carbon intensity. I think it does not make sense that the same value of 45gCO2eq *kWh-1 is considered in any region of installation. In fact that value is intended for areas of 1700kWh/m2 mean insulation value, but for example with an insulation of 1100kWh/m2 it would go up to 70gCO2eq/kWh.
My proposal would be to change the value considering the mean capacity factor of PV solar installed in the region. 

Please let me know what do you think about it.
Thanks!

**Comment by seba1337** [comment] 2022-07-02 20:54
What? PV's gCO2eq is from manufacturing PVs.

**Comment by jarek** [comment] 2022-07-04 01:33
Presumably the idea is that the emissions from manufacturing a photovoltaic panel are the same regardless if that panel is installed in Spain or in Norway (there will be some emissions to transport the panel from the factory to its destination but I'm guessing those are not very different).

But those emissions (in gCO2eq) are then amortized over expected lifetime energy production (in kWh) to get a gCO2eq/kWh figure. And the lifetime energy production can vary greatly, both because of latitude (more energy closer to equator) and because of typical weather (more energy from clear skies).

(I'm guessing "1700kWh/m2 mean insulation value" was intended to be "mean _insolation_ value"? And 1700 kWh is either a lifetime value, or intended to be 1700 W/m2?)

This is could probably be handled by the mega-issue #738 to refine emission factors per region.

**Comment by GiacomoFornaro** [comment] 2022-07-04 22:28
Yes, manufacturing emissione are amortized over lifetime energy production,
thus of the panel produces less, the value over kWh Is higher. 1700kWh/m2
is the mean yearly sum of irradiation energy value that IPCC takes into
account, see screenshot attached.
For a region with different irradiation value the emissions per kWh are
different obviously.

Hope the point is clear now
Thanks!

Il lun 4 lug 2022, 03:34 jarek ***@***.***> ha scritto:

**Comment by seba1337** [comment] 2022-07-05 06:22
In general the IPCC estimates for CO2 are a bit weird. For coal they are too low. They presume an unrealistically high efficiency of power plants, don't include CO2 needed to mine and transport coal, neither they include any CO2 for building the plant. For gas is kind of similar. No amortization of pipelines inside nor transport nor extraction lol. Even methane has lots of lots of CO2 inside, it's not pure methane. 
If it would be me, I would separate CO2 of fuel and CO2 of amorization and CO2 that just happen per year (for example CO2 for maintenance). The IPCC 2014 come from thin air. There are a lot of problems with it. For example concrete absorbs CO2 for decades, where as in their estimates they only include CO2 absorbed in concrete in 6 months (if I recall correctly). That's unrealistic, because who builds power plants that last only 6 months.

Also for solar I don't know where do they get the numbers. Solar uses now much thinner silicon now. 
From what I know: manufacutring silicon for solar panels uses a lot of CO2 not just from type of energy used (which is still usually coal!), but also because getting Si out of SiO2 uses carbon (coke) in a redox reaction, same for cleaning of Si via SiCl4, also carbon (which then makes CO2). Then you have tons of energy to melt and slowly grow the crystals, etc. and of course then you have to count also transport/mining/etc. Anyway then you most likely have also other parts of the panel, like aluminum etc. and constructing the solar plant itself. Then you have yearly maintenance, i.e. cleaning the dust of them (I think that's done manually?), changing broken solar panels due to damage (hail etc.)? No idea. 
Either way, solar makes a good cause of the approach which I've described, separating CO2 of construction and CO2 of running (fuel + maintenance). That way you could show those two figures separately and make a third (sum) out of it, then divide it by TWh produced in their lifetime. We have data for each year so that wouldn't be a problem.

**Comment by Kongkille** [comment] 2022-08-03 12:35
These are great points, we are soon starting the work on #738 and unless I am mistaken, this would also indeed be a part of it.

For the sake of getting a better overview for directly actionable issues, I am closing this one for now.

**Closed by Kongkille** 2022-08-03 12:35 UTC
Labels: science
